apiVersion: v2
name: grafana-operator
description: A Weaveworks Helm chart for the grafana-operator Profile
type: application
version: 0.0.1
dependencies:
  - name: grafana-operator
    version: "2.7.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- grafana
- operator
- monitoring


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": grafana-operator
  "weave.works/category": Analytics
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/grafana-operator/grafana-operator
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"