apiVersion: v2
name: kube-state-metrics
description: A Weaveworks Helm chart for the kube-state-metrics Profile
type: application
version: 0.0.1
dependencies:
  - name: kube-state-metrics
    version: "3.2.4"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- prometheus
- kube-state-metrics
- monitoring


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": kube-state-metrics
  "weave.works/category": Analytics
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/kube-state-metrics
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"