apiVersion: v2
name: suitecrm
description: A Weaveworks Helm chart for the suitecrm Profile
type: application
version: 0.0.1
dependencies:
  - name: suitecrm
    version: "11.2.4"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- suitecrm
- crm
- http
- web
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": suitecrm
  "weave.works/category": CRM
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/suitecrm
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"