apiVersion: v2
name: harbor
description: A Weaveworks Helm chart for the harbor Profile
type: application
version: 0.0.1
dependencies:
  - name: harbor
    version: "15.2.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- docker
- registry
- vulnerability
- scan


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": harbor
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/harbor-core
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"