apiVersion: v2
name: odoo
description: A Weaveworks Helm chart for the odoo Profile
type: application
version: 0.0.1
dependencies:
  - name: odoo
    version: "21.6.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- odoo
- crm
- www
- http
- web


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": odoo
  "weave.works/category": CRM
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/odoo
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"