apiVersion: v2
name: schema-registry
description: A Weaveworks Helm chart for the schema-registry Profile
type: application
version: 0.0.1
dependencies:
  - name: schema-registry
    version: "6.0.0"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- schema-registry
- confluent
- kafka
- zookeeper
- streaming


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": schema-registry
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/schema-registry
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"