apiVersion: v2
name: kiam
description: A Weaveworks Helm chart for the kiam Profile
type: application
version: 0.0.1
dependencies:
  - name: kiam
    version: "1.1.4"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- aws
- iam
- security


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": kiam
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/kiam
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"