apiVersion: v2
name: mariadb-galera
description: A Weaveworks Helm chart for the mariadb-galera Profile
type: application
version: 0.0.1
dependencies:
  - name: mariadb-galera
    version: "7.4.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- mariadb
- mysql
- database
- sql
- prometheus
- galera


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": mariadb-galera
  "weave.works/category": Database
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/mariadb-galera
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"