apiVersion: v2
name: rabbitmq-cluster-operator
description: A Weaveworks Helm chart for the rabbitmq-cluster-operator Profile
type: application
version: 0.0.1
dependencies:
  - name: rabbitmq-cluster-operator
    version: "3.1.0"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- rabbitmq
- operator
- infrastructure
- message queue
- AMQP


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": rabbitmq-cluster-operator
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq-cluster-operator
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"