apiVersion: v2
name: logstash
description: A Weaveworks Helm chart for the logstash Profile
type: application
version: 0.0.1
dependencies:
  - name: logstash
    version: "5.1.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- logstash
- logging
- elk


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": logstash
  "weave.works/category": LogManagement
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/logstash
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"