apiVersion: v2
name: ghost
description: A Weaveworks Helm chart for the ghost Profile
type: application
version: 0.0.1
dependencies:
  - name: ghost
    version: "19.1.20"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- ghost
- blog
- http
- web
- application
- nodejs
- javascript


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": ghost
  "weave.works/category": CMS
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/ghost
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"