apiVersion: v2
name: spring-cloud-dataflow
description: A Weaveworks Helm chart for the spring-cloud-dataflow Profile
type: application
version: 0.0.1
dependencies:
  - name: spring-cloud-dataflow
    version: "14.0.0"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- spring-cloud
- dataflow
- skipper
- spring


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": spring-cloud-dataflow
  "weave.works/category": DeveloperTools
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/spring-cloud-dataflow
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"