apiVersion: v2
name: memcached
description: A Weaveworks Helm chart for the memcached Profile
type: application
version: 0.0.1
dependencies:
  - name: memcached
    version: "6.2.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- memcached
- cache


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": memcached
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/memcached
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"