apiVersion: v2
name: fluentd
description: A Weaveworks Helm chart for the fluentd Profile
type: application
version: 0.0.1
dependencies:
  - name: fluentd
    version: "5.5.3"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- fluentd
- logging
- logs
- data
- collector


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": fluentd
  "weave.works/category": Analytics
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/fluentd
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"