apiVersion: v2
name: owncloud
description: A Weaveworks Helm chart for the owncloud Profile
type: application
version: 0.0.1
dependencies:
  - name: owncloud
    version: "12.2.4"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- owncloud
- storage
- http
- web
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": owncloud
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/owncloud
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"