apiVersion: v2
name: external-dns
description: A Weaveworks Helm chart for the external-dns Profile
type: application
version: 0.0.1
dependencies:
  - name: external-dns
    version: "6.10.2"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- external-dns
- network
- dns


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": external-dns
  "weave.works/category": DeveloperTools
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/kubernetes-sigs/external-dns
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"