apiVersion: v2
name: redis-cluster
description: A Weaveworks Helm chart for the redis-cluster Profile
type: application
version: 0.0.1
dependencies:
  - name: redis-cluster
    version: "8.2.4"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- redis
- keyvalue
- database


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": redis-cluster
  "weave.works/category": Database
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/redis
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"