apiVersion: v2
name: rabbitmq
description: A Weaveworks Helm chart for the MongoDB Profile
type: application
version: 0.0.3
dependencies:
  - name: mongodb
    version: "13.1.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- mongodb
- nosql
- database

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": mongodb
  "weave.works/category": data
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/charts/blob/master/bitnami/mongodb
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"
