apiVersion: v2
name: nginx-ingress-controller
description: A Weaveworks Helm chart for the nginx-ingress-controller Profile
type: application
version: 0.0.1
dependencies:
  - name: nginx-ingress-controller
    version: "9.3.18"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- ingress
- nginx
- http
- web
- www
- reverse proxy


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": nginx-ingress-controller
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/nginx-ingress-controller
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"