apiVersion: v2
name: wavefront
description: A Weaveworks Helm chart for the wavefront Profile
type: application
version: 0.0.1
dependencies:
  - name: wavefront
    version: "4.2.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- metric
- monitoring
- observability
- alerting


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": wavefront
  "weave.works/category": Analytics
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/wavefront-kubernetes-collector
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"