apiVersion: v2
name: dokuwiki
description: A Weaveworks Helm chart for the dokuwiki Profile
type: application
version: 0.0.1
dependencies:
  - name: dokuwiki
    version: "13.1.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- dokuwiki
- wiki
- http
- web
- application
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": dokuwiki
  "weave.works/category": Wiki
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/dokuwiki
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"