apiVersion: v2
name: testlink
description: A Weaveworks Helm chart for the testlink Profile
type: application
version: 0.0.1
dependencies:
  - name: testlink
    version: "10.0.16"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- testlink
- testing
- http
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": testlink
  "weave.works/category": DeveloperTools
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/bitnami-docker-testlink
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"