apiVersion: v2
name: parse
description: A Weaveworks Helm chart for the parse Profile
type: application
version: 0.0.1
dependencies:
  - name: parse
    version: "19.1.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- parse
- backend
- serverless
- platform
- mbaas
- mobile


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": parse
  "weave.works/category": DeveloperTools
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/parse
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"