apiVersion: v2
name: apache
description: A Weaveworks Helm chart for the apache Profile
type: application
version: 0.0.1
dependencies:
  - name: apache
    version: "9.2.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- apache
- http
- https
- www
- web
- reverse proxy


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": apache
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/apache
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"