apiVersion: v2
name: contour-operator
description: A Weaveworks Helm chart for the contour-operator Profile
type: application
version: 0.0.1
dependencies:
  - name: contour-operator
    version: "2.1.6"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- contour
- operator
- ingress
- envoy


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": contour-operator
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/projectcontour/contour-operator
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"