apiVersion: v2
name: osclass
description: A Weaveworks Helm chart for the osclass Profile
type: application
version: 0.0.1
dependencies:
  - name: osclass
    version: "14.2.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- osclass
- classifieds
- http
- web
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": osclass
  "weave.works/category": CMS
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/osclass
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"