apiVersion: v2
name: matomo
description: A Weaveworks Helm chart for the matomo Profile
type: application
version: 0.0.1
dependencies:
  - name: matomo
    version: "0.2.9"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- matomo
- analytics
- http
- web
- application
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": matomo
  "weave.works/category": Analytics
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/matomo
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"