apiVersion: v2
name: joomla
description: A Weaveworks Helm chart for the joomla Profile
type: application
version: 0.0.1
dependencies:
  - name: joomla
    version: "13.3.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- joomla
- cms
- blog
- http
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": joomla
  "weave.works/category": CMS
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/joomla
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"