apiVersion: v2
name: magento
description: A Weaveworks Helm chart for the magento Profile
type: application
version: 0.0.1
dependencies:
  - name: magento
    version: "21.1.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- magento
- e-commerce
- http
- web
- php


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": magento
  "weave.works/category": E-Commerce
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/magento
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"