apiVersion: v2
name: jupyterhub
description: A Weaveworks Helm chart for the jupyterhub Profile
type: application
version: 0.0.1
dependencies:
  - name: jupyterhub
    version: "2.0.1"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- python
- scientific


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": jupyterhub
  "weave.works/category": MachineLearning
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/jupyterhub
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"