apiVersion: v2
name: mongodb-sharded
description: A Weaveworks Helm chart for the mongodb-sharded Profile
type: application
version: 0.0.1
dependencies:
  - name: mongodb-sharded
    version: "6.1.6"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": mongodb-sharded
  "weave.works/category": Database
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/mongodb-sharded
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"