apiVersion: v1
kind: Secret
metadata:
  name: 'ci-template-registry-secret'
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}