apiVersion: v2
name: node-exporter
description: A Weaveworks Helm chart for the node-exporter Profile
type: application
version: 0.0.1
dependencies:
  - name: node-exporter
    version: "3.2.1"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- prometheus
- node-exporter
- monitoring


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": node-exporter
  "weave.works/category": Analytics
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/node-exporter
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"