apiVersion: v2
name: cert-manager
description: A Weaveworks Helm chart for the cert-manager Profile
type: application
version: 0.0.1
dependencies:
  - name: cert-manager
    version: "0.8.5"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- go
- security
- tls
- certificate


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": cert-manager
  "weave.works/category": CertificateAuthority
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/cert-manager
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"