apiVersion: v2
name: kong
description: A Weaveworks Helm chart for the kong Profile
type: application
version: 0.0.1
dependencies:
  - name: kong
    version: "7.0.0"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- kong
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": kong
  "weave.works/category": Infrastructure
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/kong
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"