apiVersion: v2
name: redis
description: A Weaveworks Helm chart for the Redis Profile
type: application
version: 0.0.3
dependencies:
  - name: redis
    version: "17.1.7"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- tekton
- tekton-pipelines
- cicd

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": redis
  "weave.works/category": data
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://bitnami.com/stack/redis/helm
    - name: Upstream Project
      url: https://bitnami.com/stack/redis/helm
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"
