apiVersion: v2
name: etcd
description: A Weaveworks Helm chart for the etcd Profile
type: application
version: 0.0.1
dependencies:
  - name: etcd
    version: "8.5.6"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/murillodigital/gitops-profiles
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- etcd
- cluster
- database
- cache
- key-value


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": etcd
  "weave.works/category": Database
  "weave.works/layer": layer-0
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/etcd
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"